### ISSUE TITLE
idea2024.1.3 debug启动项目有时会卡住

### ISSUE THREAD

**Issue by wangtaicheng** [SweetInk/jrebel-mybatisplus-idea-plugin#15]
`IntelliJ IDEA 2024.1.3 (Ultimate Edition)
Build #IU-241.17890.1, built on June 4, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 12
Registry:
  editor.minimap.enabled=true`

我本地debug启动项目时有时候会卡住，不知道什么原因，不用jrebel debug 启动就没有问题，这个我本地如何排查？

**Comment by SweetInk** [comment]
Jrebel启动时会校验License

```
"rebel-init-licensing" #54 daemon prio=5 os_prio=0 tid=0x0000024b30cd7000 nid=0x63e8 waiting for monitor entry [0x000000db493fe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.zeroturnaround.javarebel.o.a(SourceFile:26)
        - waiting to lock <0x00000005c302e740> (a java.lang.Class for com.zeroturnaround.javarebel.o)
        at com.zeroturnaround.javarebel.a.a(SourceFile:110)
        at com.zeroturnaround.javarebel.a.a(SourceFile:63)
        at com.zeroturnaround.javarebel.nl.a(SourceFile:45)
        at com.zeroturnaround.javarebel.mr.<init>(SourceFile:179)
        at com.zeroturnaround.javarebel.mr.<init>(SourceFile:172)
        at com.zeroturnaround.javarebel.mj.a(SourceFile:372)
        at com.zeroturnaround.javarebel.mj.a(SourceFile:400)
        at com.zeroturnaround.javarebel.mj.a(SourceFile:201)
        - locked <0x00000005c302e900> (a com.zeroturnaround.javarebel.mj)
        at com.zeroturnaround.javarebel.nx.a(SourceFile:32)
        at com.zeroturnaround.javarebel.nu.a(SourceFile:65)
        at com.zeroturnaround.javarebel.SDKLicensingImpl.findAndValidateLicenseFromSource(SourceFile:425)
        at com.zeroturnaround.javarebel.lf.d(SourceFile:123)
        at com.zeroturnaround.javarebel.lf.c(SourceFile:39)
        at com.zeroturnaround.javarebel.lh.run(SourceFile:92)
        at org.zeroturnaround.javarebel.integration.util.SecurityController.doWithoutSecurityManager(SourceFile:29)
        at com.zeroturnaround.javarebel.lg.run(SourceFile:87)
        at java.lang.Thread.run(Thread.java:750)
```

```
"main" #1 prio=5 os_prio=0 tid=0x0000024b06878800 nid=0x640c waiting for monitor entry [0x000000db477ff000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.zeroturnaround.javarebel.o.a(SourceFile:26)
        - waiting to lock <0x00000005c302e740> (a java.lang.Class for com.zeroturnaround.javarebel.o)
        at com.zeroturnaround.javarebel.a.a(SourceFile:110)
        at com.zeroturnaround.javarebel.a.a(SourceFile:63)
        at com.zeroturnaround.javarebel.gv.<init>(SourceFile:84)
        at com.zeroturnaround.javarebel.gr.a(SourceFile:35)
        at com.zeroturnaround.reload.b.a(SourceFile:119)
        at com.zeroturnaround.javarebel.hpf.a(SourceFile:341)
        at com.zeroturnaround.javarebel.hpf.deferredInitHook(SourceFile:184)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:40001)
```

**Comment by andresluuk** [comment]
Those stack are actually incomplete, they show that they are waiting on com.zeroturnaround.javarebel.o, but it does not show what holds the lock on com.zeroturnaround.javarebel.o. So the thread that is inside com.zeroturnaround.javarebel.o is missing from this example.

**Comment by SweetInk** [comment]
> Those stack are actually incomplete, they show that they are waiting on com.zeroturnaround.javarebel.o, but it does not show what holds the lock on com.zeroturnaround.javarebel.o. So the thread that is inside com.zeroturnaround.javarebel.o is missing from this example.

I used jstack dump to get out of the thread stack. It seems that this thread holds a `0x00000005c302e740` lock, but I don't understand why there is a difference between "Rebel Run" and "Rebel Debug" to start the application. Obviously "Rebel Debug" will cause the main thread to get stuck for a while

```
"rebel-IDENotificationsImpl-PostCycle" #51 daemon prio=5 os_prio=0 tid=0x0000024b30cdd000 nid=0xb12c runnable [0x000000db494fc000]
   java.lang.Thread.State: RUNNABLE
        at com.zeroturnaround.jrebelbase.facade.a.arrayLength(SourceFile)
        at java.util.Arrays.copyOf(Arrays.java:3213)
        at com.zeroturnaround.jrebelbase.facade.a.copyOf(SourceFile:317)
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:267)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
        at java.util.ArrayList.add(ArrayList.java:464)
        at sun.security.util.ManifestEntryVerifier.setEntry(ManifestEntryVerifier.java:149)
        at java.util.jar.JarVerifier.beginEntry(JarVerifier.java:190)
        at java.util.jar.JarVerifier$VerifierStream.<init>(JarVerifier.java:459)
        at java.util.jar.JarFile.getInputStream(JarFile.java:491)
        - locked <0x000000071697b158> (a sun.net.www.protocol.jar.URLJarFile)
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:476)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:371)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:297)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
        - locked <0x00000005c3036e58> (a java.lang.Class for javax.crypto.JceSecurity)
        at javax.crypto.JceSecurity.canUseProvider(JceSecurity.java:204)
        at javax.crypto.Cipher.getInstance(Cipher.java:518)
        at sun.security.ssl.JsseJce.getCipher(JsseJce.java:189)
        at sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
        at sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
        at sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:81)
        at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:69)
        at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:345)
        at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:46)
        at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:577)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.security.Provider$Service.getImplClass(Provider.java:1728)
        at java.security.Provider$Service.newInstance(Provider.java:1686)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at com.zeroturnaround.jrebel.bundled.org.apache.hc.core5.ssl.c.a(SourceFile:474)
        at com.zeroturnaround.javarebel.o.a(SourceFile:28)
        - locked <0x00000005c302e740> (a java.lang.Class for com.zeroturnaround.javarebel.o)
        at com.zeroturnaround.javarebel.a.a(SourceFile:110)
        at com.zeroturnaround.javarebel.a.a(SourceFile:63)
        at com.zeroturnaround.javarebel.qa.a(SourceFile:82)
        at com.zeroturnaround.javarebel.qa.a(SourceFile:56)
        at com.zeroturnaround.javarebel.qa$$Lambda$32/977674685.getHttpClient(Unknown Source)
        at com.zeroturnaround.javarebel.qf.run(SourceFile:185)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by andresluuk** [comment]
There is a lot here, so I will try to take it 1 by 1.
First the main difference with "Rebel Run" and "Rebel Debug". With debugger it starts up the JVM with debugger flags and debugger attached, this means JVM disables some optimizations and is not that aggressive with jit (or something like that) so this means the startup might be a little slower across the board.

Now to the fact the this "rebel-IDENotificationsImpl-PostCycle" thread is slow. The SSLContext load might always be slow, but now with the debugger it's even slower and that's why you notice it.
It might also be that normally it's done after some other stuff so the main thread does not get stuck on it.
So anyway one way to get rid of this thread would be add the following flag:
-Drebel.notification.disable=true
But this does not rule out that some other thread gets stuck behind the initial init of SSLContext.

Now I went back to your original stack dumps and the main issue is that the "main" thread gets stuck behind the slow thread.
Luckily I toke a look into the place the main thread gets stuck at. It is basically creating a new thread to load of some work into it and gets stuck on the SSLContext stuff in the constructor of the Thread.
So I moved the code a few lines lower to be done inside the newly created thread.
Could you download the latest nightly build of jrebel and try it out with it.
https://www.jrebel.com/products/jrebel/download/nightly-build
Does the main thread still get stuck somewhere or behind SSLContext in some other place even with the nightly build?
Also please wait for **1h** from now before trying it out, as it will take 30 for fix I made into jrebel to be public.

**Comment by SweetInk** [comment]
Today, I launched the application using the "Jrebel Debug" method, and it is no longer stuck. If the above problem occurs again, I will try the solution you provided.

**Comment by wangtaicheng** [comment]
> Today, I launched the application using the "Jrebel Debug" method, and it is no longer stuck. If the above problem occurs again, I will try the solution you provided.

本地需要做什么？

**Comment by wangtaicheng** [comment]
> Today, I launched the application using the "Jrebel Debug" method, and it is no longer stuck. If the above problem occurs again, I will try the solution you provided.

本地需要做什么？

**Comment by BigBlueBaby** [comment]
https://blog.csdn.net/lj1272416334/article/details/134872386 亲测有用！一次启动了
